### ISSUE TITLE
C source code in MSL 3.2.2 Beta 2 does not compile on MinGW

### ISSUE THREAD

**Issue by modelica-trac-importer** [modelica/Modelica#1925]
**Reported by peter&#x2e;lundberg on 25 Feb 2016 12:23 UTC**
When trying to compile on MinGW on Windows with gcc 4.8.1, I get:

- ModelicaInternal.c

Issue:
```
  ModelicaInternal.c:882:22: error: conflicting types for 'ModelicaInternaleadFile'
  MODELICA_EXPORT void ModelicaInternal_readFile(const char* fileName, const char* string[], size_t nLines) {
ModelicaInternal.c:260:22: note: previous declaration of 'ModelicaInterna
readFile' was here
  MODELICA_EXPORT void ModelicaInternal_readFile(_In_z_ const char* fileName, ...
```

Solution: Add **defined<ins>MINGW32</ins>)**
```
#if !defined(__ATTR_SAL) || defined(__MINGW32__)
#define _In_z_
#define _Out_
#endif
```

  - ModelicaMatIO.c
Issue 1.Missing guard (added below):
```
   #ifndef __USE_MINGW_ANSI_STDIO 1
   #define __USE_MINGW_ANSI_STDIO 1
   #endif
```

Issue 2:

```
ModelicaMatIO.c:8484:17: error: conflicting types for 'size_t'
  #define SSIZE_T size_t
 e:\mingw\lib\gcc\mingw32\4.8.1\include\stddef.h:212:23: note: previous declaration of 'size_t' was here
  typedef __SIZE_TYPE__ size_t;
```

Cause (found no solution):
```
#ifndef SSIZE_T
#define SSIZE_T size_t
#endif  /* !defined(SSIZE_T) */
```

----

Migrated-From: https://trac.modelica.org/Modelica/ticket/1925

**Comment by modelica-trac-importer** [comment]
**Modified by beutlich on 25 Feb 2016 12:31 UTC**

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 25 Feb 2016 12:34 UTC**
Please test if the issues are resolved if you use the current trunk head.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 25 Feb 2016 12:56 UTC**
`__ATTR_SAL` is not defined by MinGW. Thus it should not be necessary to explicitely add `defined(__MINGW32__)` to this case.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 25 Feb 2016 13:23 UTC**
I fixed the warnings if compiled in pedantic mode. See https://github.com/tbeu/ModelicaStandardTables/commit/df3ba2d16f5b30804f37dc8b3e38fea88d84dfbc

However I cannot reproduce the error `conflicting types for 'size_t'`. Please state the command line how to compile ModelicaMatIO.c.

**Comment by modelica-trac-importer** [comment]
**Comment by peter&#46;lundberg on 26 Feb 2016 13:54 UTC**
Replying to [comment:3 beutlich]:
> `__ATTR_SAL` is not defined by MinGW. Thus it should not be necessary to explicitely add `defined(__MINGW32__)` to this case.

Indeed `__ATR_SAL`  is not defined when I test a simple hello world program on MinGW. However, the "!|| defined<ins>MINGW32</ins>)" made a difference in my setup (StandAloneDymosim project). I don't know what caused it. But I'll come back with a new ticket if issue still present in next version.

**Comment by modelica-trac-importer** [comment]
**Comment by peter&#x2e;lundberg on 26 Feb 2016 13:56 UTC**
To test again requires a new merge of the trunk with Dymolas local modifications, which I have no time for this week. If you cannot reporduce, feel free to close the ticket and I'll be back with more details if the issue remains in next version.

**Comment by modelica-trac-importer** [comment]
**Comment by beutlich on 26 Feb 2016 14:48 UTC**
Fixed GCC pedantic warnings of ModelicaMatIO (on MinGW and Linux) by 397ab1288fc5df4fc6f3586e460b89146bb0db3e and d9ce97f1cd1cb7e762be4abe03f787d463b361b9.
